version: "3.8"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  server:
    build:
      context: ..
      target: base
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/mcp
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RAG_ASYNC_INGEST: "1"
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ..
      target: worker
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/mcp
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

